### PR TITLE
Minor package updates

### PR DESCRIPTION
**Pull request by eddelbuettel**
This fixes two nags I noticed from `R CMD check` against the master branch.  Neither is consquential so feel free to ignore and close.  A few nags remain in documentation entries but I reckon you are aware and on top of it.

### CODE REVIEW

**Comment by johnkerl** [comment]
LGTM, thanks @eddelbuettel !!

> A few nags remain in documentation entries but I reckon you are aware and on top of it.

If you mean that `R CMD check` complains about missing `Author` and `Maintainer` while we do have `Authors@R` ...  I should figure out how to get to it to accept the syntax we prefer (`Authors@R`), not the syntax it prefers ........ :^/

**Review by johnkerl — APPROVED** [review]
Thanks!

**Comment by eddelbuettel** [comment]
No, here is the tail with the remaining noise I see:

```
[.... earlier stuff omitted ...]
✔  checking R code for possible problems (3.8s)
✔  checking Rd files (1.1s)                                                                              
✔  checking Rd metadata ...         
W  checking Rd cross-references (560ms)                                                                  
   Missing link or links in documentation object 'QueryRanges.Rd':                                       
     ‘array[numeric]’                                                                                    
                                    
   See section 'Cross-references' in the 'Writing R Extensions' manual.
✔  checking for missing documentation entries (890ms)
✔  checking for code/documentation mismatches (3s)
W  checking Rd \usage sections (382ms)                                                                   
   Undocumented arguments in documentation object '.get_decoded_response_body_or_stop'                   
     ‘result_format’                                                                                     
                    
   Undocumented arguments in documentation object 'list_arrays'  
     ‘...’     
                                             
   Undocumented arguments in documentation object 'register_udf'                                         
     ‘func_text’                                  
   Documented arguments not in \usage in documentation object 'register_udf':
     ‘exec_raw’                                                                                          
                                                                                                         
   Undocumented arguments in documentation object 'update_udf_info'                                      
     ‘func_text’                                                                                                                                                                                                   
   Documented arguments not in \usage in documentation object 'update_udf_info':                                                                                                                                   
     ‘exec_raw’                                                                                                                                                                                                    
                                                                                                                                                                                                                   
   Functions with \usage entries need to have the appropriate \alias                                                                                                                                               
   entries, and all their arguments documented.                                                                                                                                                                    
   The \usage entries must correspond to syntactically valid R code.                                                                                                                                               
   See chapter ‘Writing R documentation files’ in the ‘Writing R                                                                                                                                                   
   Extensions’ manual.                                                                                                                                                                                             
W  checking Rd contents (2.2s)                                                                           
   Argument items with no description in Rd object 'execute_array_udf':                                                                                                                                            
     ‘attrs’                                                                                             
                                                                                                                                                                                                                   
✔  checking for unstated dependencies in examples (422ms)              
✔  checking installed files from ‘inst/doc’ ...
✔  checking files in ‘vignettes’ ...
✔  checking examples (1.3s)   
[... later stuff omitted ...]
```

I remember from way-back-when that the `array[numeric]` nag is 'tax' we pay for using OpenAPI but the others look like they are addressable.

**Comment by johnkerl** [comment]
@eddelbuettel sorry to be naive but do you mind to include the command you issued which produced the above output?

All I get is:

```
$ R CMD check .
* using log directory ‘/Users/johnkerl/git/TileDB-Inc/TileDB-Cloud-R/..Rcheck’
* using R version 4.1.2 (2021-11-01)
* using platform: x86_64-apple-darwin17.0 (64-bit)
* using session charset: UTF-8
* checking for file ‘./DESCRIPTION’ ... ERROR
Required fields missing or empty:
  ‘Author’ ‘Maintainer’
* DONE

Status: 1 ERROR
See
  ‘/Users/johnkerl/git/TileDB-Inc/TileDB-Cloud-R/..Rcheck/00check.log’
for details.
```

**Comment by eddelbuettel** [comment]
Happy to take this up on slack, we don't have to this here.

**Comment by johnkerl** [comment]
Awesome feedback, thanks @eddelbuettel for leveling up my R-fu!! :D

**Comment by eddelbuettel** [comment]
It's mostly just "folklore" and a learned habit of obscure tasks and options documented in tomes long disappeared in the tunnels of time...

**Comment by johnkerl** [comment]
@eddelbuettel thanks for surfacing!! The more people know, the better :)

**Pull request merged**
